version: "3"

services:
    postgres_db:
        build: .
        restart: always
        ports:
            - "15432:5432"
        networks:
            - postgres-compose-network

    admin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@usp.br"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "9002:80"
        depends_on:
            - postgres_db
        networks:
            - postgres-compose-network

networks:
    postgres-compose-network:
        driver: bridge
