version: "3"

services:
    postgres_db:
        build: .
        ports:
            - "15432:5432"
        environment:
            POSTGRES_PASSWORD: "ribamar"
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        networks:
            - postgres-compose-network

    admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@usp.br"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "9002:80"
        depends_on:
            - postgres_db
        networks:
            - postgres-compose-network

networks:
    postgres-compose-network:
        driver: bridge
